# Generated by Django 4.1.7 on 2023-03-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Content name')),
                ('text', models.TextField(verbose_name='Content text')),
                ('img', models.ImageField(upload_to='images', verbose_name='Content image')),
                ('button_name', models.CharField(max_length=20, verbose_name='Content button name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user_info',
            options={'verbose_name': 'User_Info', 'verbose_name_plural': 'Users_Info'},
        ),
    ]
