# Generated by Django 4.1.7 on 2023-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_content_alter_user_info_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Whats name')),
                ('whats_text', models.TextField(verbose_name='Whats text')),
            ],
        ),
    ]
