# Generated by Django 4.1.7 on 2023-03-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_whats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Skill name')),
                ('text', models.TextField(verbose_name='Skill text')),
                ('img', models.ImageField(upload_to='images', verbose_name='Skill image')),
            ],
        ),
    ]
