# Generated by Django 4.1.7 on 2023-03-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Protfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20, verbose_name='Image name1')),
                ('name2', models.CharField(max_length=20, verbose_name='Image name2')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
            ],
        ),
    ]
