# Generated by Django 4.1.7 on 2023-03-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_image_protfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Contact name')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact email')),
                ('subject', models.CharField(max_length=200, verbose_name='Contact subject')),
                ('message', models.TextField(verbose_name='Contact message')),
            ],
        ),
    ]
