# Generated by Django 4.1.7 on 2023-03-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User name')),
                ('proff', models.CharField(max_length=60, verbose_name='User proff')),
                ('img', models.ImageField(upload_to='images', verbose_name='User image')),
            ],
        ),
    ]
